name: Run Serenity Tests

on:
  push:
    branches: 'master'
  pull_request:
    branches: 'master'

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Serenity tests
        run: ./gradlew clean test aggregate

      - name: Upload Serenity Report
        uses: actions/upload-artifact@v3
        with:
          name: serenity-report
          path: build/reports/serenity
